//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skills
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public skills()
        {
            this.kpis = new HashSet<kpis>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public int llistes_skills_id { get; set; }
        public bool actiu { get; set; }
        public int colorFondo { get; set; }
        public int colorTexto { get; set; }
    
        public virtual llistes_skills llistes_skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kpis> kpis { get; set; }
    }
}
