//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Models
{
    using System;
    using System.Collections.Generic;

    public partial class usuaris
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuaris()
        {
            this.grups_has_alumnes = new HashSet<grups_has_alumnes>();
            this.grups_has_docents = new HashSet<grups_has_docents>();
            this.valoracions = new HashSet<valoracions>();
            this.valoracions1 = new HashSet<valoracions>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public int rols_id { get; set; }
        public bool actiu { get; set; }
        public string correo { get; set; }
        public string contrasenya { get; set; }
        public string cognoms { get; set; }
        public string nomUsuari { get; set; }
        public string imagen { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grups_has_alumnes> grups_has_alumnes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grups_has_docents> grups_has_docents { get; set; }
        public virtual rols rols { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<valoracions> valoracions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<valoracions> valoracions1 { get; set; }
    }
}
