//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificacions
    {
        public int id { get; set; }
        public int usuaris_id { get; set; }
        public string missatge { get; set; }
    
        public virtual usuaris usuaris { get; set; }
    }
}
